merge stg to prod
ncc-erp/ncc-erp-talent-v2 pull request #14
Opened 2023-11-21 06:25 UTC by huybuidoanquang

2023-11-21 07:37 UTC, khanh-lesy commented on angular/src/app/modules/admin/mail/edit-mail-dialog/edit-mail-dialog.component.html
ddd

2023-11-21 07:51 UTC, duynxncc requested changes

2023-11-21 07:51 UTC, duynxncc commented on aspnet-core/src/TalentV2.Core/DomainServices/Reports/Dtos/ReportEducationHaveCVPassInterViewDto.cs
> +    {
why does it exist?

2023-11-21 07:51 UTC, duynxncc commented on aspnet-core/src/TalentV2.Core/DomainServices/Reports/Dtos/OverviewHiringDto.cs
> +        public string displayName { get; set; }
pascal case

2023-11-21 07:51 UTC, duynxncc commented on angular/src/shared/shared.module.ts
> +import {ExportDialogComponent} from './components/export-dialog/export-dialog.component'
format consitency, space after and before {}

2023-11-21 07:56 UTC, khanh-lesy commented on angular/src/shared/shared.module.ts
> +import {ExportDialogComponent} from './components/export-dialog/export-dialog.component'
yes, I will pay more attention

2023-11-21 09:22 UTC, khanh-lesy commented on aspnet-core/src/TalentV2.Core/DomainServices/Reports/Dtos/OverviewHiringDto.cs
> +        public string displayName { get; set; }
yes, I will pay more attention

2023-11-21 10:03 UTC, khanh-lesy commented on aspnet-core/src/TalentV2.Core/DomainServices/Reports/Dtos/ReportEducationHaveCVPassInterViewDto.cs
> +    {
Do I need to repair it?

2023-11-22 09:23 UTC, duynxncc approved these changes

2023-11-22 11:51 UTC, merged